{% set name = "wwt_jupyterlab_extension" %}
{% set version = "1.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wwt_jupyterlab_extension-{{ version }}.tar.gz
  sha256: 9d2aca453e13e86c203cd7ed295aaa5c5b959977913d4692b08a85047b4eeea8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - wwt_jupyterlab_extension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WorldWideTelescope/wwt-jupyterlab
  summary: Prebuilt AAS WorldWide Telescope JupyterLab extension
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
