{% set name = "wwt_jupyterlab_extension" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wwt_jupyterlab_extension-{{ version }}.tar.gz
  sha256: f59d8e7df73e0174dbfa47fb933400aa7b1e6e5152a16d0880aebcbdbda1bfe6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.5
    - hatch-jupyter-builder >=0.8
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - wwt_jupyterlab_extension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WorldWideTelescope/wwt-jupyterlab
  summary: Prebuilt WorldWide Telescope JupyterLab extension
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
